-- ============================================================================
-- Reemplazo del catalogo de musica fitness (music_tracks) v2
-- Cardio, Fuerza y Running renovados 100% con musica electronica de tendencia
-- (house/EDM/bass/dubstep). Yoga se mantiene tranquila/acustica sin cambios.
-- Cada video fue verificado embeddable (oEmbed) y probado en reproduccion real.
-- Ejecutar en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).
-- ============================================================================

DELETE FROM public.music_tracks;

INSERT INTO public.music_tracks (title, artist, platform, url, category, bpm)
VALUES
('I''m Good (Blue)', 'David Guetta & Bebe Rexha', 'YouTube', 'https://www.youtube.com/embed/90RLzVUuXe4', 'cardio_hiit', 128),
('Piece Of Your Heart', 'Meduza ft. Goodboys', 'YouTube', 'https://www.youtube.com/embed/KWjV25q34Hw', 'cardio_hiit', 124),
('Losing It', 'Fisher', 'YouTube', 'https://www.youtube.com/embed/o3WdLtpWM_c', 'cardio_hiit', 126),
('Where You Are', 'John Summit & Hayla', 'YouTube', 'https://www.youtube.com/embed/5BqjhUmldDc', 'cardio_hiit', 125),
('Do It To It', 'ACRAZE ft. Cherish', 'YouTube', 'https://www.youtube.com/embed/6wwuEXlIniU', 'cardio_hiit', 128),
('The Business', 'Tiësto', 'YouTube', 'https://www.youtube.com/embed/nCg3ufihKyU', 'cardio_hiit', 120),
('How Deep Is Your Love', 'Calvin Harris & Disciples', 'YouTube', 'https://www.youtube.com/embed/EgqUJOudrcM', 'cardio_hiit', 121),
('Higher Love', 'Kygo & Whitney Houston', 'YouTube', 'https://www.youtube.com/embed/JR49dyo-y0E', 'cardio_hiit', 103),
('Words', 'Alesso ft. Zara Larsson', 'YouTube', 'https://www.youtube.com/embed/zIJEOEZdLzE', 'cardio_hiit', 128),
('Moth To A Flame', 'Swedish House Mafia & The Weeknd', 'YouTube', 'https://www.youtube.com/embed/u9n7Cw-4_HQ', 'cardio_hiit', 100),
('Miracle Maker', 'Dom Dolla ft. Clementine Douglas', 'YouTube', 'https://www.youtube.com/embed/U6Xz8foh7XQ', 'cardio_hiit', 124),
('Stay', 'Zedd & Alessia Cara', 'YouTube', 'https://www.youtube.com/embed/h--P8HzYZ74', 'cardio_hiit', 102),
('On My Mind', 'Diplo & SIDEPIECE', 'YouTube', 'https://www.youtube.com/embed/TAKR_6vNJR8', 'cardio_hiit', 126),
('Cold Heart', 'Elton John & Dua Lipa (PNAU Remix)', 'YouTube', 'https://www.youtube.com/embed/qod03PVTLqk', 'cardio_hiit', 116),
('Todo De Ti', 'Rauw Alejandro', 'YouTube', 'https://www.youtube.com/embed/CFPLIaMpGrY', 'cardio_hiit', 92),
('Party', 'Bad Bunny ft. Rauw Alejandro', 'YouTube', 'https://www.youtube.com/embed/G9XrXnfJPsk', 'cardio_hiit', 92),
('Provenza', 'Karol G', 'YouTube', 'https://www.youtube.com/embed/ca48oMV59LU', 'cardio_hiit', 95),
('Luna', 'Feid', 'YouTube', 'https://www.youtube.com/embed/x2oUajHp8pg', 'cardio_hiit', 94),
('Baby Don''t Hurt Me', 'David Guetta, Anne-Marie & Coi Leray', 'YouTube', 'https://www.youtube.com/embed/k3DBmAlUh1A', 'cardio_hiit', 127),
('Feels', 'Calvin Harris ft. Pharrell Williams, Katy Perry, Big Sean', 'YouTube', 'https://www.youtube.com/embed/ozv4q2ov3Mk', 'cardio_hiit', 100),
('Happier', 'Marshmello ft. Bastille', 'YouTube', 'https://www.youtube.com/embed/m7Bc3pLyij0', 'cardio_hiit', 100),
('No Money', 'Galantis', 'YouTube', 'https://www.youtube.com/embed/xUVz4nRmxn4', 'cardio_hiit', 100),
('Body', 'Loud Luxury ft. Brando', 'YouTube', 'https://www.youtube.com/embed/IetIg7y5k3A', 'cardio_hiit', 120),
('Ride It', 'Regard', 'YouTube', 'https://www.youtube.com/embed/ucVUEmjKsko', 'cardio_hiit', 97),
('In The Name Of Love', 'Martin Garrix & Bebe Rexha', 'YouTube', 'https://www.youtube.com/embed/RnBT9uUYb1w', 'cardio_hiit', 100),
('X Rated', 'Excision & Space Laces', 'YouTube', 'https://www.youtube.com/embed/SuNVWDVz7zM', 'fuerza', 150),
('Nuclear', 'Zomboy', 'YouTube', 'https://www.youtube.com/embed/GGKPiTFmzrw', 'fuerza', 140),
('Internet Friends', 'Knife Party', 'YouTube', 'https://www.youtube.com/embed/luJJBeCFeM0', 'fuerza', 128),
('Blind Faith', 'Chase & Status ft. Liam Bailey', 'YouTube', 'https://www.youtube.com/embed/zYpDJw7fThU', 'fuerza', 175),
('Disconnected', 'Pegboard Nerds', 'YouTube', 'https://www.youtube.com/embed/MwSkC85TDgY', 'fuerza', 150),
('I Can''t Stop', 'Flux Pavilion', 'YouTube', 'https://www.youtube.com/embed/3Q9rewnLFYw', 'fuerza', 140),
('Bangarang', 'Skrillex ft. Sirah', 'YouTube', 'https://www.youtube.com/embed/YJVmu6yttiw', 'fuerza', 110),
('Scary Monsters and Nice Sprites', 'Skrillex', 'YouTube', 'https://www.youtube.com/embed/WSeNSzJ2-Jw', 'fuerza', 140),
('Drown', 'Bring Me The Horizon', 'YouTube', 'https://www.youtube.com/embed/TkV5709EG5M', 'fuerza', 150),
('Tsunami', 'DVBBS & Borgeous', 'YouTube', 'https://www.youtube.com/embed/0EWbonj7f18', 'fuerza', 128),
('Spaceman', 'Hardwell', 'YouTube', 'https://www.youtube.com/embed/lETmskoqh30', 'fuerza', 128),
('Never Say Goodbye', 'Hardwell & Dyro', 'YouTube', 'https://www.youtube.com/embed/Co3w_ZxcO1U', 'fuerza', 128),
('Bigfoot', 'W&W', 'YouTube', 'https://www.youtube.com/embed/9ytt1ELA82U', 'fuerza', 150),
('Mammoth', 'Dimitri Vegas & Like Mike, W&W', 'YouTube', 'https://www.youtube.com/embed/_o-XIryB2gg', 'fuerza', 128),
('Secrets', 'Tiësto & KSHMR ft. Vassy', 'YouTube', 'https://www.youtube.com/embed/Dr1nN__-2Po', 'fuerza', 128),
('Turn Down for What', 'DJ Snake & Lil Jon', 'YouTube', 'https://www.youtube.com/embed/HMUDVMiITOU', 'fuerza', 100),
('Delirious (Boneless)', 'Steve Aoki, Chris Lake & Tujamo', 'YouTube', 'https://www.youtube.com/embed/gl2p4G3CUrI', 'fuerza', 128),
('Freaks', 'Timmy Trumpet & Savage', 'YouTube', 'https://www.youtube.com/embed/r1dquH_KOQc', 'fuerza', 150),
('Bonfire', 'Knife Party', 'YouTube', 'https://www.youtube.com/embed/e-IWRmpefzE', 'fuerza', 145),
('Spectre', 'Alan Walker', 'YouTube', 'https://www.youtube.com/embed/wJnBTPUQS5A', 'fuerza', 128),
('Love Is Gone', 'SLANDER', 'YouTube', 'https://www.youtube.com/embed/HiXx5JFRxb4', 'fuerza', 150),
('Gold (Stupid Love)', 'Illenium & Excision', 'YouTube', 'https://www.youtube.com/embed/FcuMd_N7mmA', 'fuerza', 150),
('Hypnocurrency', 'REZZ & deadmau5', 'YouTube', 'https://www.youtube.com/embed/RT2No1vusjg', 'fuerza', 128),
('Terror Squad', 'Zomboy', 'YouTube', 'https://www.youtube.com/embed/p6eER7elUPs', 'fuerza', 150),
('The Paradox', 'Excision', 'YouTube', 'https://www.youtube.com/embed/HbNIKR2pctU', 'fuerza', 140),
('Don''t Let Me Down', 'The Chainsmokers ft. Daya', 'YouTube', 'https://www.youtube.com/embed/Io0fBr1XBUA', 'running_cycling', 160),
('Wake Me Up', 'Avicii', 'YouTube', 'https://www.youtube.com/embed/IcrbM1l_BoI', 'running_cycling', 124),
('Animals', 'Martin Garrix', 'YouTube', 'https://www.youtube.com/embed/gCYcHz2k5x0', 'running_cycling', 128),
('Don''t You Worry Child', 'Swedish House Mafia', 'YouTube', 'https://www.youtube.com/embed/1y6smkh6c-0', 'running_cycling', 129),
('Firestone', 'Kygo ft. Conrad Sewell', 'YouTube', 'https://www.youtube.com/embed/9Sc-ir2UwGU', 'running_cycling', 120),
('Clarity', 'Zedd ft. Foxes', 'YouTube', 'https://www.youtube.com/embed/IxxstCcJlsc', 'running_cycling', 128),
('Blinding Lights', 'The Weeknd', 'YouTube', 'https://www.youtube.com/embed/4NRXx6U8ABQ', 'running_cycling', 171),
('Harder, Better, Faster, Stronger', 'Daft Punk', 'YouTube', 'https://www.youtube.com/embed/gAjR4_CbPpQ', 'running_cycling', 123),
('Summer', 'Calvin Harris', 'YouTube', 'https://www.youtube.com/embed/ebXbLfLACGM', 'running_cycling', 126),
('Faded', 'Alan Walker', 'YouTube', 'https://www.youtube.com/embed/60ItHLz5WEA', 'running_cycling', 90),
('Alone', 'Marshmello', 'YouTube', 'https://www.youtube.com/embed/ALZHF5UqnU4', 'running_cycling', 140),
('Titanium', 'David Guetta ft. Sia', 'YouTube', 'https://www.youtube.com/embed/JRfuAukYTKg', 'running_cycling', 126),
('Red Lights', 'Tiësto', 'YouTube', 'https://www.youtube.com/embed/CFF0mV24WCY', 'running_cycling', 128),
('Levels', 'Avicii', 'YouTube', 'https://www.youtube.com/embed/_ovdm2yX4MA', 'running_cycling', 126),
('Sugar', 'Robin Schulz ft. Francesco Yates', 'YouTube', 'https://www.youtube.com/embed/bvC_0foemLY', 'running_cycling', 120),
('Rather Be', 'Clean Bandit ft. Jess Glynne', 'YouTube', 'https://www.youtube.com/embed/m-M1AtrxztU', 'running_cycling', 115),
('Physical', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/9HDEHj2yzew', 'running_cycling', 146),
('Runaway (U & I)', 'Galantis', 'YouTube', 'https://www.youtube.com/embed/5XR7naZ_zZA', 'running_cycling', 128),
('Don''t Start Now', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/oygrmJFKYZY', 'running_cycling', 124),
('Ocean Drive', 'Duke Dumont', 'YouTube', 'https://www.youtube.com/embed/KDxJlW6cxRk', 'running_cycling', 120),
('Whole Heart', 'Gryffin ft. Bipolar Sunshine', 'YouTube', 'https://www.youtube.com/embed/PWhMoGt0cs8', 'running_cycling', 100),
('Say My Name', 'ODESZA ft. Zyra', 'YouTube', 'https://www.youtube.com/embed/HdzI-191xhU', 'running_cycling', 142),
('Never Be Like You', 'Flume ft. Kai', 'YouTube', 'https://www.youtube.com/embed/Ly7uj0JwgKg', 'running_cycling', 100),
('Good Things Fall Apart', 'Illenium ft. Jon Bellion', 'YouTube', 'https://www.youtube.com/embed/XpmeVNxZ-Ks', 'running_cycling', 150),
('Language', 'Porter Robinson', 'YouTube', 'https://www.youtube.com/embed/Vsy1URDYK88', 'running_cycling', 128),
('Come Away With Me', 'Norah Jones', 'YouTube', 'https://www.youtube.com/embed/lbjZPFBD6JU', 'yoga_recovery', 75),
('Skinny Love', 'Bon Iver', 'YouTube', 'https://www.youtube.com/embed/ssdgFoHLwnk', 'yoga_recovery', 78),
('Better Together', 'Jack Johnson', 'YouTube', 'https://www.youtube.com/embed/seZMOTGCDag', 'yoga_recovery', 85),
('Keep Your Head Up', 'Ben Howard', 'YouTube', 'https://www.youtube.com/embed/ADP65wbBUpc', 'yoga_recovery', 90),
('Heartbeats', 'José González', 'YouTube', 'https://www.youtube.com/embed/HxJhYpTIrl8', 'yoga_recovery', 80),
('Flightless Bird, American Mouth', 'Iron & Wine', 'YouTube', 'https://www.youtube.com/embed/xwZNGaMrwcE', 'yoga_recovery', 70),
('Bloom', 'The Paper Kites', 'YouTube', 'https://www.youtube.com/embed/8inJtTG_DuU', 'yoga_recovery', 82),
('White Winter Hymnal', 'Fleet Foxes', 'YouTube', 'https://www.youtube.com/embed/DrQRS40OKNE', 'yoga_recovery', 85),
('The Blower''s Daughter', 'Damien Rice', 'YouTube', 'https://www.youtube.com/embed/5YXVMCHG-Nk', 'yoga_recovery', 65),
('Nuvole Bianche', 'Ludovico Einaudi', 'YouTube', 'https://www.youtube.com/embed/4VR-6AS0-l4', 'yoga_recovery', 60),
('On The Nature of Daylight', 'Max Richter', 'YouTube', 'https://www.youtube.com/embed/rVN1B-tUpgs', 'yoga_recovery', 55),
('Hoppípolla', 'Sigur Rós', 'YouTube', 'https://www.youtube.com/embed/JAYb8ZyjzD0', 'yoga_recovery', 78),
('Near Light', 'Ólafur Arnalds', 'YouTube', 'https://www.youtube.com/embed/0kYc55bXJFI', 'yoga_recovery', 60),
('River Flows In You', 'Yiruma', 'YouTube', 'https://www.youtube.com/embed/7maJOI3QMu0', 'yoga_recovery', 70),
('Only Time', 'Enya', 'YouTube', 'https://www.youtube.com/embed/7wfYIMyS_dI', 'yoga_recovery', 80),
('Says', 'Nils Frahm', 'YouTube', 'https://www.youtube.com/embed/dIwwjy4slI8', 'yoga_recovery', 65),
('An Ending (Ascent)', 'Brian Eno', 'YouTube', 'https://www.youtube.com/embed/OlaTeXX3uH8', 'yoga_recovery', 50),
('Riverside', 'Agnes Obel', 'YouTube', 'https://www.youtube.com/embed/vjncyiuwwXQ', 'yoga_recovery', 75),
('Apocalypse', 'Cigarettes After Sex', 'YouTube', 'https://www.youtube.com/embed/sElE_BfQ67s', 'yoga_recovery', 68),
('Ocean Eyes', 'Billie Eilish', 'YouTube', 'https://www.youtube.com/embed/viimfQi_pUw', 'yoga_recovery', 76),
('The Night We Met', 'Lord Huron', 'YouTube', 'https://www.youtube.com/embed/KtlgYxa6BMU', 'yoga_recovery', 78),
('Anchor', 'Novo Amor', 'YouTube', 'https://www.youtube.com/embed/OmKAn8rNbKg', 'yoga_recovery', 72),
('Open', 'Rhye', 'YouTube', 'https://www.youtube.com/embed/sng_CdAAw8M', 'yoga_recovery', 80),
('Weightless', 'Marconi Union', 'YouTube', 'https://www.youtube.com/embed/UfcAVejslrU', 'yoga_recovery', 60),
('Holocene', 'Bon Iver', 'YouTube', 'https://www.youtube.com/embed/TWcyIpul8OE', 'yoga_recovery', 78);
