-- ============================================================================
-- Reemplazo del catalogo de musica fitness (music_tracks)
-- Generado automaticamente: 100 canciones de tendencia verificadas (embeddable
-- via YouTube oEmbed) distribuidas en las 4 categorias del reproductor.
-- Ejecutar en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).
-- ============================================================================

DELETE FROM public.music_tracks;

INSERT INTO public.music_tracks (title, artist, platform, url, category, bpm)
VALUES
('Houdini', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/suAR1PYFNYA', 'cardio_hiit', 117),
('Espresso', 'Sabrina Carpenter', 'YouTube', 'https://www.youtube.com/embed/eVli-tstM5E', 'cardio_hiit', 110),
('Greedy', 'Tate McRae', 'YouTube', 'https://www.youtube.com/embed/To4SWGZkEPk', 'cardio_hiit', 111),
('Water', 'Tyla', 'YouTube', 'https://www.youtube.com/embed/XoiOOiuH8iI', 'cardio_hiit', 117),
('Lil Boo Thang', 'Paul Russell', 'YouTube', 'https://www.youtube.com/embed/5AgDZcM8In8', 'cardio_hiit', 114),
('Padam Padam', 'Kylie Minogue', 'YouTube', 'https://www.youtube.com/embed/p6Cnazi_Fi0', 'cardio_hiit', 128),
('Miracle', 'Calvin Harris & Ellie Goulding', 'YouTube', 'https://www.youtube.com/embed/961v0E3b01g', 'cardio_hiit', 143),
('Rush', 'Troye Sivan', 'YouTube', 'https://www.youtube.com/embed/b53QJYP-lqY', 'cardio_hiit', 126),
('Dance The Night', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/OiC1rgCPmUQ', 'cardio_hiit', 110),
('TQG', 'Karol G & Shakira', 'YouTube', 'https://www.youtube.com/embed/jZGpkLElSu8', 'cardio_hiit', 100),
('MONACO', 'Bad Bunny', 'YouTube', 'https://www.youtube.com/embed/_PJvpq8uOZM', 'cardio_hiit', 95),
('Feliz Cumpleaños Ferxxo', 'Feid', 'YouTube', 'https://www.youtube.com/embed/jRxDUsGmwuc', 'cardio_hiit', 95),
('Provenza', 'Karol G', 'YouTube', 'https://www.youtube.com/embed/ca48oMV59LU', 'cardio_hiit', 104),
('Todo De Ti', 'Rauw Alejandro', 'YouTube', 'https://www.youtube.com/embed/CFPLIaMpGrY', 'cardio_hiit', 106),
('Ella Baila Sola', 'Peso Pluma & Eslabon Armado', 'YouTube', 'https://www.youtube.com/embed/lZiaYpD9ZrI', 'cardio_hiit', 132),
('Shakira: Bzrp Music Sessions Vol. 53', 'Shakira & Bizarrap', 'YouTube', 'https://www.youtube.com/embed/CocEMWdc7Ck', 'cardio_hiit', 122),
('I''m Good (Blue)', 'David Guetta & Bebe Rexha', 'YouTube', 'https://www.youtube.com/embed/90RLzVUuXe4', 'cardio_hiit', 128),
('Yes, And?', 'Ariana Grande', 'YouTube', 'https://www.youtube.com/embed/eB6txyhHFG4', 'cardio_hiit', 124),
('Levitating', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/TUVcZfQe-Kw', 'cardio_hiit', 103),
('Seven', 'Jung Kook ft. Latto', 'YouTube', 'https://www.youtube.com/embed/QU9c0053UAU', 'cardio_hiit', 124),
('BREAK MY SOUL', 'Beyoncé', 'YouTube', 'https://www.youtube.com/embed/yjki-9Pthh0', 'cardio_hiit', 115),
('Quevedo: Bzrp Music Sessions Vol. 52', 'Bizarrap & Quevedo', 'YouTube', 'https://www.youtube.com/embed/A_g3lMcWVy0', 'cardio_hiit', 128),
('Ay Vamos', 'J Balvin', 'YouTube', 'https://www.youtube.com/embed/TapXs54Ah3E', 'cardio_hiit', 92),
('Taki Taki', 'DJ Snake ft. Selena Gomez, Ozuna, Cardi B', 'YouTube', 'https://www.youtube.com/embed/ixkoVwKQaJg', 'cardio_hiit', 95),
('Envolver', 'Anitta', 'YouTube', 'https://www.youtube.com/embed/hFCjGiawJi4', 'cardio_hiit', 100),
('Till I Collapse', 'Eminem', 'YouTube', 'https://www.youtube.com/embed/Obim8BYGnOE', 'fuerza', 171),
('Dreams and Nightmares', 'Meek Mill', 'YouTube', 'https://www.youtube.com/embed/S8gfqs1-NuE', 'fuerza', 83),
('HUMBLE.', 'Kendrick Lamar', 'YouTube', 'https://www.youtube.com/embed/tvTRZJ-4EyI', 'fuerza', 150),
('POWER', 'Kanye West', 'YouTube', 'https://www.youtube.com/embed/L53gjP-TtGE', 'fuerza', 154),
('X Gon'' Give It To Ya', 'DMX', 'YouTube', 'https://www.youtube.com/embed/fGx6K90TmCI', 'fuerza', 130),
('Paint The Town Red', 'Doja Cat', 'YouTube', 'https://www.youtube.com/embed/m4_9TFeMfJE', 'fuerza', 120),
('Enter Sandman', 'Metallica', 'YouTube', 'https://www.youtube.com/embed/CD-E-LDc384', 'fuerza', 123),
('Lose Yourself', 'Eminem', 'YouTube', 'https://www.youtube.com/embed/xFYQQPAOz7Y', 'fuerza', 171),
('SICKO MODE', 'Travis Scott', 'YouTube', 'https://www.youtube.com/embed/6ONRf7h3Mdk', 'fuerza', 155),
('God''s Plan', 'Drake', 'YouTube', 'https://www.youtube.com/embed/xpVfcZ0ZcFM', 'fuerza', 77),
('In Da Club', '50 Cent', 'YouTube', 'https://www.youtube.com/embed/5qm8PH4xAss', 'fuerza', 90),
('Not Like Us', 'Kendrick Lamar', 'YouTube', 'https://www.youtube.com/embed/H58vbez_m4E', 'fuerza', 101),
('Like That', 'Future, Metro Boomin & Kendrick Lamar', 'YouTube', 'https://www.youtube.com/embed/N9bKBAA22Go', 'fuerza', 140),
('Killing In The Name', 'Rage Against The Machine', 'YouTube', 'https://www.youtube.com/embed/bWXazVhlyxQ', 'fuerza', 91),
('Thunderstruck', 'AC/DC', 'YouTube', 'https://www.youtube.com/embed/v2AC41dglnM', 'fuerza', 133),
('Believer', 'Imagine Dragons', 'YouTube', 'https://www.youtube.com/embed/7wtfhZwyrcc', 'fuerza', 125),
('In The End', 'Linkin Park', 'YouTube', 'https://www.youtube.com/embed/eVTXPUF4Oz4', 'fuerza', 105),
('Chop Suey!', 'System of a Down', 'YouTube', 'https://www.youtube.com/embed/CSvFpBOe8eY', 'fuerza', 127),
('Industry Baby', 'Jack Harlow & Lil Nas X', 'YouTube', 'https://www.youtube.com/embed/UTHLKHL_whs', 'fuerza', 149),
('Turn Down for What', 'DJ Snake & Lil Jon', 'YouTube', 'https://www.youtube.com/embed/HMUDVMiITOU', 'fuerza', 100),
('Animal I Have Become', 'Three Days Grace', 'YouTube', 'https://www.youtube.com/embed/xqds0B_meys', 'fuerza', 137),
('Wow.', 'Post Malone', 'YouTube', 'https://www.youtube.com/embed/393C3pr2ioY', 'fuerza', 99),
('Bodak Yellow', 'Cardi B', 'YouTube', 'https://www.youtube.com/embed/PEGccV-NOm8', 'fuerza', 125),
('Bad and Boujee', 'Migos ft. Lil Uzi Vert', 'YouTube', 'https://www.youtube.com/embed/S-sJp1FfG7Q', 'fuerza', 125),
('Remember the Name', 'Fort Minor', 'YouTube', 'https://www.youtube.com/embed/VDvr08sCPOc', 'fuerza', 85),
('Don''t Let Me Down', 'The Chainsmokers ft. Daya', 'YouTube', 'https://www.youtube.com/embed/Io0fBr1XBUA', 'running_cycling', 160),
('Wake Me Up', 'Avicii', 'YouTube', 'https://www.youtube.com/embed/IcrbM1l_BoI', 'running_cycling', 124),
('Animals', 'Martin Garrix', 'YouTube', 'https://www.youtube.com/embed/DuFUtL8zUAk', 'running_cycling', 128),
('Don''t You Worry Child', 'Swedish House Mafia', 'YouTube', 'https://www.youtube.com/embed/1y6smkh6c-0', 'running_cycling', 129),
('Firestone', 'Kygo ft. Conrad Sewell', 'YouTube', 'https://www.youtube.com/embed/9Sc-ir2UwGU', 'running_cycling', 120),
('Clarity', 'Zedd ft. Foxes', 'YouTube', 'https://www.youtube.com/embed/IxxstCcJlsc', 'running_cycling', 128),
('Blinding Lights', 'The Weeknd', 'YouTube', 'https://www.youtube.com/embed/4NRXx6U8ABQ', 'running_cycling', 171),
('Harder, Better, Faster, Stronger', 'Daft Punk', 'YouTube', 'https://www.youtube.com/embed/gAjR4_CbPpQ', 'running_cycling', 123),
('Summer', 'Calvin Harris', 'YouTube', 'https://www.youtube.com/embed/ebXbLfLACGM', 'running_cycling', 126),
('Faded', 'Alan Walker', 'YouTube', 'https://www.youtube.com/embed/60ItHLz5WEA', 'running_cycling', 90),
('Alone', 'Marshmello', 'YouTube', 'https://www.youtube.com/embed/ALZHF5UqnU4', 'running_cycling', 140),
('Titanium', 'David Guetta ft. Sia', 'YouTube', 'https://www.youtube.com/embed/JRfuAukYTKg', 'running_cycling', 126),
('Red Lights', 'Tiësto', 'YouTube', 'https://www.youtube.com/embed/CFF0mV24WCY', 'running_cycling', 128),
('Good Feeling', 'Flo Rida', 'YouTube', 'https://www.youtube.com/embed/3OnnDqH6Wj8', 'running_cycling', 128),
('Levels', 'Avicii', 'YouTube', 'https://www.youtube.com/embed/_ovdm2yX4MA', 'running_cycling', 126),
('Adventure Of A Lifetime', 'Coldplay', 'YouTube', 'https://www.youtube.com/embed/QtXby3twMmI', 'running_cycling', 109),
('Radioactive', 'Imagine Dragons', 'YouTube', 'https://www.youtube.com/embed/ktvTqknDobU', 'running_cycling', 136),
('Counting Stars', 'OneRepublic', 'YouTube', 'https://www.youtube.com/embed/hT_nvWreIhg', 'running_cycling', 122),
('Right Here, Right Now', 'Fatboy Slim', 'YouTube', 'https://www.youtube.com/embed/ub747pprmJ8', 'running_cycling', 127),
('Sugar', 'Robin Schulz ft. Francesco Yates', 'YouTube', 'https://www.youtube.com/embed/bvC_0foemLY', 'running_cycling', 120),
('Rather Be', 'Clean Bandit ft. Jess Glynne', 'YouTube', 'https://www.youtube.com/embed/m-M1AtrxztU', 'running_cycling', 115),
('Physical', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/9HDEHj2yzew', 'running_cycling', 146),
('Runaway (U & I)', 'Galantis', 'YouTube', 'https://www.youtube.com/embed/5XR7naZ_zZA', 'running_cycling', 128),
('Don''t Start Now', 'Dua Lipa', 'YouTube', 'https://www.youtube.com/embed/oygrmJFKYZY', 'running_cycling', 124),
('Party Rock Anthem', 'LMFAO', 'YouTube', 'https://www.youtube.com/embed/KQ6zr6kCPj8', 'running_cycling', 130),
('Come Away With Me', 'Norah Jones', 'YouTube', 'https://www.youtube.com/embed/lbjZPFBD6JU', 'yoga_recovery', 75),
('Skinny Love', 'Bon Iver', 'YouTube', 'https://www.youtube.com/embed/ssdgFoHLwnk', 'yoga_recovery', 78),
('Better Together', 'Jack Johnson', 'YouTube', 'https://www.youtube.com/embed/seZMOTGCDag', 'yoga_recovery', 85),
('Keep Your Head Up', 'Ben Howard', 'YouTube', 'https://www.youtube.com/embed/ADP65wbBUpc', 'yoga_recovery', 90),
('Heartbeats', 'José González', 'YouTube', 'https://www.youtube.com/embed/HxJhYpTIrl8', 'yoga_recovery', 80),
('Flightless Bird, American Mouth', 'Iron & Wine', 'YouTube', 'https://www.youtube.com/embed/xwZNGaMrwcE', 'yoga_recovery', 70),
('Bloom', 'The Paper Kites', 'YouTube', 'https://www.youtube.com/embed/8inJtTG_DuU', 'yoga_recovery', 82),
('White Winter Hymnal', 'Fleet Foxes', 'YouTube', 'https://www.youtube.com/embed/DrQRS40OKNE', 'yoga_recovery', 85),
('The Blower''s Daughter', 'Damien Rice', 'YouTube', 'https://www.youtube.com/embed/5YXVMCHG-Nk', 'yoga_recovery', 65),
('Nuvole Bianche', 'Ludovico Einaudi', 'YouTube', 'https://www.youtube.com/embed/4VR-6AS0-l4', 'yoga_recovery', 60),
('On The Nature of Daylight', 'Max Richter', 'YouTube', 'https://www.youtube.com/embed/rVN1B-tUpgs', 'yoga_recovery', 55),
('Hoppípolla', 'Sigur Rós', 'YouTube', 'https://www.youtube.com/embed/JAYb8ZyjzD0', 'yoga_recovery', 78),
('Near Light', 'Ólafur Arnalds', 'YouTube', 'https://www.youtube.com/embed/0kYc55bXJFI', 'yoga_recovery', 60),
('River Flows In You', 'Yiruma', 'YouTube', 'https://www.youtube.com/embed/7maJOI3QMu0', 'yoga_recovery', 70),
('Only Time', 'Enya', 'YouTube', 'https://www.youtube.com/embed/7wfYIMyS_dI', 'yoga_recovery', 80),
('Says', 'Nils Frahm', 'YouTube', 'https://www.youtube.com/embed/dIwwjy4slI8', 'yoga_recovery', 65),
('An Ending (Ascent)', 'Brian Eno', 'YouTube', 'https://www.youtube.com/embed/OlaTeXX3uH8', 'yoga_recovery', 50),
('Riverside', 'Agnes Obel', 'YouTube', 'https://www.youtube.com/embed/vjncyiuwwXQ', 'yoga_recovery', 75),
('Apocalypse', 'Cigarettes After Sex', 'YouTube', 'https://www.youtube.com/embed/sElE_BfQ67s', 'yoga_recovery', 68),
('Ocean Eyes', 'Billie Eilish', 'YouTube', 'https://www.youtube.com/embed/viimfQi_pUw', 'yoga_recovery', 76),
('The Night We Met', 'Lord Huron', 'YouTube', 'https://www.youtube.com/embed/KtlgYxa6BMU', 'yoga_recovery', 78),
('Anchor', 'Novo Amor', 'YouTube', 'https://www.youtube.com/embed/OmKAn8rNbKg', 'yoga_recovery', 72),
('Open', 'Rhye', 'YouTube', 'https://www.youtube.com/embed/sng_CdAAw8M', 'yoga_recovery', 80),
('Weightless', 'Marconi Union', 'YouTube', 'https://www.youtube.com/embed/UfcAVejslrU', 'yoga_recovery', 60),
('Holocene', 'Bon Iver', 'YouTube', 'https://www.youtube.com/embed/TWcyIpul8OE', 'yoga_recovery', 78);
